export default {
  product: [
    {
      id: 1,
      productTitle: "Basil",
      image: "http://www.tablespoonfoods.com/images/Rasam%20Masala_Front.png",
      url: "https://www.google.com/",
      title: "Full Stack Developer",
      description:
        "Basil is a well-known name for the culinary herb. Would like to make your pizza or salad smell and taste differently and intriguing, basil will manage this task. This is a",
      price: "$10.00",
      availability: true,
      productType: "bunch",
      productSpec: "Harvest 2015",
      info: "Harvest 2015 | In stock | Bunch",
    },
    {
      id: 2,
      productTitle: "Basil",
      image: "http://www.tablespoonfoods.com/images/Rasam%20Masala_Front.png",
      url: "https://www.google.com/",
      title: "Full Stack Developer",
      description:
        "Basil is a well-known name for the culinary herb. Would like to make your pizza or salad smell and taste differently and intriguing, basil will manage this task. This is a",
      price: "$10.00",
      availability: false,
      productType: "bunch",
      productSpec: "Harvest 2015",
      info: "Harvest 2015 | In stock | Bunch",
    },
    {
      id: 3,
      productTitle: "Basil",
      image: "http://www.tablespoonfoods.com/images/Rasam%20Masala_Front.png",
      url: "https://www.google.com/",
      title: "Full Stack Developer",
      description:
        "Basil is a well-known name for the culinary herb. Would like to make your pizza or salad smell and taste differently and intriguing, basil will manage this task. This is a",
      price: "$10.00",
      availability: true,
      productType: "bunch",
      productSpec: "Harvest 2015",
      info: "Harvest 2015 | In stock | Bunch",
    },
    {
      id: 4,
      productTitle: "Basil",
      image: "http://www.tablespoonfoods.com/images/Rasam%20Masala_Front.png",
      url: "https://www.google.com/",
      title: "Full Stack Developer",
      description:
        "Basil is a well-known name for the culinary herb. Would like to make your pizza or salad smell and taste differently and intriguing, basil will manage this task. This is a",
      price: "$10.00",
      availability: true,
      productType: "bunch",
      productSpec: "Harvest 2015",
      info: "Harvest 2015 | In stock | Bunch",
    },
    {
      id: 5,
      productTitle: "Basil",
      image: "http://www.tablespoonfoods.com/images/Rasam%20Masala_Front.png",
      url: "https://www.google.com/",
      title: "Full Stack Developer",
      description:
        "Basil is a well-known name for the culinary herb. Would like to make your pizza or salad smell and taste differently and intriguing, basil will manage this task. This is a",
      price: "$10.00",
      availability: false,
      productType: "bunch",
      productSpec: "Harvest 2015",
      info: "Harvest 2015 | In stock | Bunch",
    },
  ],
  collections: [
    {
      id: 1,
      name: "Rasam Masala",
      image: "http://www.tablespoonfoods.com/images/Rasam%20Masala_Front.png",
      to: "collection_a",
    },
    {
      id: 2,
      name: "Collection B",
      image: "http://www.tablespoonfoods.com/images/Rasam%20Masala_Front.png",
      to: "collection_b",
    },
    {
      id: 3,
      name: "Collection C",
      image: "http://www.tablespoonfoods.com/images/Rasam%20Masala_Front.png",
      to: "collection_c",
    },
    {
      id: 4,
      name: "Collection D",
      image: "http://www.tablespoonfoods.com/images/Rasam%20Masala_Front.png",
      to: "collection_d",
    },
    {
      id: 5,
      name: "Collection E",
      image: "http://www.tablespoonfoods.com/images/Rasam%20Masala_Front.png",
      to: "collection_e",
    },
    {
      id: 6,
      name: "Collection F",
      image: "http://www.tablespoonfoods.com/images/Rasam%20Masala_Front.png",
      to: "collection_f",
    },
  ],
};
